const Theme = {
  MAIN: '#F7DA76',
  SUB_ORANGE: '#FFA471',
  SUB_PINK: '#E3928F',

  MAIN_FONT: '#3D3D3D',
  DISABLED_FONT: '#8E8E8E',

  MAIN_GRAY: '#767676',
  DISABLED_BTN_FONT: '#8E8E8E',
  PLACEHOLDER: '#BDBDBD',
  BORDER: '#BDBDBD',
  SHADOW_BORDER: '#DBDBDB',
  ERROR: '#DE504B',
  SECTION_BG: '#F2F2F2',
  WHITE: '#ffffff',
};

export default Theme;
